[package]
name = "git-store-forward"
version = "0.1.0"
authors = ["Dom Rodriguez <shymega@shymega.org.uk>"]
edition = "2018"

[[bin]]
name = "git-store-forward"

[lib]
name = "git_store_forward"
path = "src/lib.rs"

[dependencies]
